function PMAUVB = Skyggeprosjekt_import_PMA_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PMAUVB25082021 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PMAUVB25082021 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  PMAUVB = Skyggeprosjekt_import_PMA_file("L:\Optisk Lab\Uvnet\Prosjekter\Skyggeprosjekt\2021\Målinger\PMA_UVB_25082021.log", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Aug-2021 10:08:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["DetektorType", "SN", "loggerdato", "loggertid", "mleverdi", "Var6", "Var7", "Var8", "Var9"];
opts.SelectedVariableNames = ["DetektorType", "SN", "loggerdato", "loggertid", "mleverdi"];
opts.VariableTypes = ["double", "double", "datetime", "datetime", "double", "char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var6", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var6", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "loggerdato", "InputFormat", "dd.MM.yyyy");
opts = setvaropts(opts, "loggertid", "InputFormat", "HH:mm:ss");

% Import the data
PMAUVB = readtable(filename, opts);

end