function [fitresult, gof] = skyggeprosjekt_create_exp_Fit(xData, yData)
%CREATEFIT(XDATA,YDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xData
%      Y Output: yData
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Aug-2021 15:29:48


%% Fit: 'untitled fit 1'.
[xData_1, yData_1] = prepareCurveData( xData, yData );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [2.70484832737868 0.0255039847537004 0.109293212637299 1.49851309913427];

% Fit model to data.
[fitresult, gof] = fit( xData_1, yData_1, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData_1, yData_1 );
legend( h, 'yData vs. xData', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'xData', 'Interpreter', 'none' );
ylabel( 'yData', 'Interpreter', 'none' );
grid on


