function UVBios = Skyggeprosjekt_import_UVBios_file(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UVBIOSKOLBOTN2425AUGUST1 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  UVBios = Skyggeprosjekt_import_UVBios_file(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
% UVBios = Skyggeprosjekt_import_UVBios_file("L:\Optisk Lab\Uvnet\Prosjekter\Skyggeprosjekt\2021\Målinger\UVBios_Kolbotn_24-25_august_2021.log", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Aug-2021 11:38:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Time", "AVGBio0616", "AVGFin3724", "Temp1", "Temp2"];
opts.VariableTypes = ["datetime", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Time", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "dd.MM.yyyy");

% Import the data
UVBios = readtable(filename, opts);

end